name: Consolidated CI/CD Pipeline
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Build Frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          
      # Upload Artifacts
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/out'

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment: { name: github-pages }
    steps:
      - uses: actions/deploy-pages@v4
